pipeline {
    agent any

    stages {
        stage('clone project') {
            steps {
                git branch: 'master', url: 'https://github.com/tsarjun/Amazon.git'
            }
        }

        stage('List files') {
            steps {
                sh 'ls -R'
            }
        }

        stage('clean') {
            steps {
                dir('Amazon/Amazon-core') {   // <-- folder containing pom.xml
                    sh 'mvn clean'
                }
            }
        }

        stage('compile') {
            steps {
                dir('Amazon/Amazon') {
                    sh 'mvn compile'
                }
            }
        }

        stage('test') {
            steps {
                dir('Amazon/Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('build') {
            steps {
                dir('Amazon/Amazon') {
                    sh 'mvn clean install'
                }
            }
        }
    } // closes stages
} // closes pipeline
